name: sauna-sim
base: core24
title: {{app.binaryName}}
website: {{app.homepage}}
version: '{{app.version}}'
summary: {{app.shortDesc}} # 79 char long summary
license: GPL-3.0+
description: |
  SaunaSim is an ATC Training tool that simulates an aircraft with a full FMS and autopilot. The aircraft are
  designed to act as realistically as possible and take into account various factors such as atmospheric and performance data.

grade: stable
confinement: strict

layout:
  /usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_ON/webkit2gtk-4.1:
    bind: $SNAP/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_ON/webkit2gtk-4.1
  /etc/profile.d:
    bind: $SNAP_DATA/etc/profile.d

apps:
  sauna-sim:
    command: usr/bin/{{app.binaryName}}
    desktop: usr/share/applications/{{app.binaryName}}.desktop
    extensions: [gnome]
    plugs:
      - network
      - network-bind
      - network-status
      - network-observe
    # Add whatever plugs you need here, see https://snapcraft.io/docs/snapcraft-interfaces for more info.
    # The gnome extension already includes [ desktop, desktop-legacy, gsettings, opengl, wayland, x11, mount-observe, calendar-service ]

package-repositories:
  - type: apt
    components: [main]
    suites: [noble]
    key-id: 78E1918602959B9C59103100F1831DDAFC42E99D
    url: http://ppa.launchpad.net/snappy-dev/snapcraft-daily/ubuntu

parts:
  build-app:
    plugin: dump
    build-packages:
      - dpkg
    stage-packages:
      - libwebkit2gtk-4.1-0
      - libayatana-appindicator3-1
    source: .
    override-build: |
      set -eu
      dpkg -x SaunaSim.deb $SNAPCRAFT_PART_INSTALL/
      sed -i -e "s|Icon={{app.binaryName}}|Icon=/usr/share/icons/hicolor/32x32/apps/{{app.binaryName}}.png|g" $SNAPCRAFT_PART_INSTALL/usr/share/applications/{{app.binaryName}}.desktop